#!/bin/bash

set -e

# This script renders RMarkdown files before committing them

if [[ $(uname) == "Linux" ]]; then
    exe=/mnt/d/Tools/R/R-4.2.0/bin/x64/Rscript.exe
else
    exe='D:/Tools/R/R-4.2.0/bin/x64/Rscript.exe'
fi

#echo $exe

# Define the file types to be checked
file_types=(Rmd)

# Loop through the staged files
for file_type in "${file_types[@]}"; do
	oldIFS="$IFS"
	IFS=$'\n'
    for file_name in $(git diff --cached --name-only --diff-filter=ACMR "*.$file_type"); do
        # Check if the file has been modified
        if [ -f "$file_name" ]; then
            # Render the RMarkdown file
			mdFile="${file_name%.$file_type}.md"
			# rmarkdown automatically replace the spaces with '-'
			# in the output files, so I output the result filename
			# into file 'tmp1' and picked up by git later
            $exe -e \
			"outFile<-rmarkdown::render('$file_name',output_dir=dirname('$file_name')); cat(outFile,file='tmp1')" || exit 2
            # Add the rendered file to the staging area
			git add "$(cat tmp1)" && rm tmp1
		else
			echo "File $file_name doesn't exist"
			exit 1
        fi
    done
done

# Exit with success
exit 0
